apiVersion: v1
kind: Service #What kind of object you want to create
metadata: #service name,Data that helps uniquely identify the object
  name: homems
spec: #What state you desire for the object
  selector:
    app: homems
  ports:
    - port: 8009  #port at which service is internally available
      targetPort: 8009 #port of container
 #     nodePort: 30002  # port at which service is externally available  range 30000- 32767 
      name: homems
  type: LoadBalancer